/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as cartLayoutImport } from './routes/(cart)/_layout'
import { Route as appLayoutImport } from './routes/(app)/_layout'
import { Route as appLayoutIndexImport } from './routes/(app)/_layout/index'
import { Route as cartLayoutCartImport } from './routes/(cart)/_layout/cart'
import { Route as appLayoutAboutImport } from './routes/(app)/_layout/about'
import { Route as appLayoutNotauthenticatedImport } from './routes/(app)/_layout/_not_authenticated'
import { Route as appLayoutAuthenticatedImport } from './routes/(app)/_layout/_authenticated'
import { Route as appLayoutNotauthenticatedSignUpImport } from './routes/(app)/_layout/_not_authenticated/sign-up'
import { Route as appLayoutNotauthenticatedSignInImport } from './routes/(app)/_layout/_not_authenticated/sign-in'
import { Route as appLayoutShopItemHandleImport } from './routes/(app)/_layout/shop/item/$handle'
import { Route as appLayoutAuthenticatedProfileLayoutImport } from './routes/(app)/_layout/_authenticated/profile/_layout'
import { Route as appLayoutAuthenticatedProfileLayoutIndexImport } from './routes/(app)/_layout/_authenticated/profile/_layout/index'
import { Route as appLayoutAuthenticatedProfileLayoutEditImport } from './routes/(app)/_layout/_authenticated/profile/_layout/edit'
import { Route as appLayoutAuthenticatedProfileLayoutChangePasswordImport } from './routes/(app)/_layout/_authenticated/profile/_layout/change-password'

// Create Virtual Routes

const cartImport = createFileRoute('/(cart)')()
const appImport = createFileRoute('/(app)')()
const appLayoutAuthenticatedProfileImport = createFileRoute(
  '/(app)/_layout/_authenticated/profile',
)()

// Create/Update Routes

const cartRoute = cartImport.update({
  id: '/(cart)',
  getParentRoute: () => rootRoute,
} as any)

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const cartLayoutRoute = cartLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => cartRoute,
} as any)

const appLayoutRoute = appLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => appRoute,
} as any)

const appLayoutIndexRoute = appLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)

const cartLayoutCartRoute = cartLayoutCartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => cartLayoutRoute,
} as any)

const appLayoutAboutRoute = appLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appLayoutRoute,
} as any)

const appLayoutNotauthenticatedRoute = appLayoutNotauthenticatedImport.update({
  id: '/_not_authenticated',
  getParentRoute: () => appLayoutRoute,
} as any)

const appLayoutAuthenticatedRoute = appLayoutAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => appLayoutRoute,
} as any)

const appLayoutAuthenticatedProfileRoute =
  appLayoutAuthenticatedProfileImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => appLayoutAuthenticatedRoute,
  } as any)

const appLayoutNotauthenticatedSignUpRoute =
  appLayoutNotauthenticatedSignUpImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => appLayoutNotauthenticatedRoute,
  } as any)

const appLayoutNotauthenticatedSignInRoute =
  appLayoutNotauthenticatedSignInImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => appLayoutNotauthenticatedRoute,
  } as any)

const appLayoutShopItemHandleRoute = appLayoutShopItemHandleImport.update({
  id: '/shop/item/$handle',
  path: '/shop/item/$handle',
  getParentRoute: () => appLayoutRoute,
} as any)

const appLayoutAuthenticatedProfileLayoutRoute =
  appLayoutAuthenticatedProfileLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => appLayoutAuthenticatedProfileRoute,
  } as any)

const appLayoutAuthenticatedProfileLayoutIndexRoute =
  appLayoutAuthenticatedProfileLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutAuthenticatedProfileLayoutRoute,
  } as any)

const appLayoutAuthenticatedProfileLayoutEditRoute =
  appLayoutAuthenticatedProfileLayoutEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => appLayoutAuthenticatedProfileLayoutRoute,
  } as any)

const appLayoutAuthenticatedProfileLayoutChangePasswordRoute =
  appLayoutAuthenticatedProfileLayoutChangePasswordImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => appLayoutAuthenticatedProfileLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutImport
      parentRoute: typeof appRoute
    }
    '/(cart)': {
      id: '/(cart)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof cartImport
      parentRoute: typeof rootRoute
    }
    '/(cart)/_layout': {
      id: '/(cart)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof cartLayoutImport
      parentRoute: typeof cartRoute
    }
    '/(app)/_layout/_authenticated': {
      id: '/(app)/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutAuthenticatedImport
      parentRoute: typeof appLayoutImport
    }
    '/(app)/_layout/_not_authenticated': {
      id: '/(app)/_layout/_not_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutNotauthenticatedImport
      parentRoute: typeof appLayoutImport
    }
    '/(app)/_layout/about': {
      id: '/(app)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appLayoutAboutImport
      parentRoute: typeof appLayoutImport
    }
    '/(cart)/_layout/cart': {
      id: '/(cart)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof cartLayoutCartImport
      parentRoute: typeof cartLayoutImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexImport
      parentRoute: typeof appLayoutImport
    }
    '/(app)/_layout/_not_authenticated/sign-in': {
      id: '/(app)/_layout/_not_authenticated/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof appLayoutNotauthenticatedSignInImport
      parentRoute: typeof appLayoutNotauthenticatedImport
    }
    '/(app)/_layout/_not_authenticated/sign-up': {
      id: '/(app)/_layout/_not_authenticated/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof appLayoutNotauthenticatedSignUpImport
      parentRoute: typeof appLayoutNotauthenticatedImport
    }
    '/(app)/_layout/_authenticated/profile': {
      id: '/(app)/_layout/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appLayoutAuthenticatedProfileImport
      parentRoute: typeof appLayoutAuthenticatedImport
    }
    '/(app)/_layout/_authenticated/profile/_layout': {
      id: '/(app)/_layout/_authenticated/profile/_layout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appLayoutAuthenticatedProfileLayoutImport
      parentRoute: typeof appLayoutAuthenticatedProfileRoute
    }
    '/(app)/_layout/shop/item/$handle': {
      id: '/(app)/_layout/shop/item/$handle'
      path: '/shop/item/$handle'
      fullPath: '/shop/item/$handle'
      preLoaderRoute: typeof appLayoutShopItemHandleImport
      parentRoute: typeof appLayoutImport
    }
    '/(app)/_layout/_authenticated/profile/_layout/change-password': {
      id: '/(app)/_layout/_authenticated/profile/_layout/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof appLayoutAuthenticatedProfileLayoutChangePasswordImport
      parentRoute: typeof appLayoutAuthenticatedProfileLayoutImport
    }
    '/(app)/_layout/_authenticated/profile/_layout/edit': {
      id: '/(app)/_layout/_authenticated/profile/_layout/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof appLayoutAuthenticatedProfileLayoutEditImport
      parentRoute: typeof appLayoutAuthenticatedProfileLayoutImport
    }
    '/(app)/_layout/_authenticated/profile/_layout/': {
      id: '/(app)/_layout/_authenticated/profile/_layout/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof appLayoutAuthenticatedProfileLayoutIndexImport
      parentRoute: typeof appLayoutAuthenticatedProfileLayoutImport
    }
  }
}

// Create and export the route tree

interface appLayoutAuthenticatedProfileLayoutRouteChildren {
  appLayoutAuthenticatedProfileLayoutChangePasswordRoute: typeof appLayoutAuthenticatedProfileLayoutChangePasswordRoute
  appLayoutAuthenticatedProfileLayoutEditRoute: typeof appLayoutAuthenticatedProfileLayoutEditRoute
  appLayoutAuthenticatedProfileLayoutIndexRoute: typeof appLayoutAuthenticatedProfileLayoutIndexRoute
}

const appLayoutAuthenticatedProfileLayoutRouteChildren: appLayoutAuthenticatedProfileLayoutRouteChildren =
  {
    appLayoutAuthenticatedProfileLayoutChangePasswordRoute:
      appLayoutAuthenticatedProfileLayoutChangePasswordRoute,
    appLayoutAuthenticatedProfileLayoutEditRoute:
      appLayoutAuthenticatedProfileLayoutEditRoute,
    appLayoutAuthenticatedProfileLayoutIndexRoute:
      appLayoutAuthenticatedProfileLayoutIndexRoute,
  }

const appLayoutAuthenticatedProfileLayoutRouteWithChildren =
  appLayoutAuthenticatedProfileLayoutRoute._addFileChildren(
    appLayoutAuthenticatedProfileLayoutRouteChildren,
  )

interface appLayoutAuthenticatedProfileRouteChildren {
  appLayoutAuthenticatedProfileLayoutRoute: typeof appLayoutAuthenticatedProfileLayoutRouteWithChildren
}

const appLayoutAuthenticatedProfileRouteChildren: appLayoutAuthenticatedProfileRouteChildren =
  {
    appLayoutAuthenticatedProfileLayoutRoute:
      appLayoutAuthenticatedProfileLayoutRouteWithChildren,
  }

const appLayoutAuthenticatedProfileRouteWithChildren =
  appLayoutAuthenticatedProfileRoute._addFileChildren(
    appLayoutAuthenticatedProfileRouteChildren,
  )

interface appLayoutAuthenticatedRouteChildren {
  appLayoutAuthenticatedProfileRoute: typeof appLayoutAuthenticatedProfileRouteWithChildren
}

const appLayoutAuthenticatedRouteChildren: appLayoutAuthenticatedRouteChildren =
  {
    appLayoutAuthenticatedProfileRoute:
      appLayoutAuthenticatedProfileRouteWithChildren,
  }

const appLayoutAuthenticatedRouteWithChildren =
  appLayoutAuthenticatedRoute._addFileChildren(
    appLayoutAuthenticatedRouteChildren,
  )

interface appLayoutNotauthenticatedRouteChildren {
  appLayoutNotauthenticatedSignInRoute: typeof appLayoutNotauthenticatedSignInRoute
  appLayoutNotauthenticatedSignUpRoute: typeof appLayoutNotauthenticatedSignUpRoute
}

const appLayoutNotauthenticatedRouteChildren: appLayoutNotauthenticatedRouteChildren =
  {
    appLayoutNotauthenticatedSignInRoute: appLayoutNotauthenticatedSignInRoute,
    appLayoutNotauthenticatedSignUpRoute: appLayoutNotauthenticatedSignUpRoute,
  }

const appLayoutNotauthenticatedRouteWithChildren =
  appLayoutNotauthenticatedRoute._addFileChildren(
    appLayoutNotauthenticatedRouteChildren,
  )

interface appLayoutRouteChildren {
  appLayoutAuthenticatedRoute: typeof appLayoutAuthenticatedRouteWithChildren
  appLayoutNotauthenticatedRoute: typeof appLayoutNotauthenticatedRouteWithChildren
  appLayoutAboutRoute: typeof appLayoutAboutRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
  appLayoutShopItemHandleRoute: typeof appLayoutShopItemHandleRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutAuthenticatedRoute: appLayoutAuthenticatedRouteWithChildren,
  appLayoutNotauthenticatedRoute: appLayoutNotauthenticatedRouteWithChildren,
  appLayoutAboutRoute: appLayoutAboutRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
  appLayoutShopItemHandleRoute: appLayoutShopItemHandleRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface appRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface cartLayoutRouteChildren {
  cartLayoutCartRoute: typeof cartLayoutCartRoute
}

const cartLayoutRouteChildren: cartLayoutRouteChildren = {
  cartLayoutCartRoute: cartLayoutCartRoute,
}

const cartLayoutRouteWithChildren = cartLayoutRoute._addFileChildren(
  cartLayoutRouteChildren,
)

interface cartRouteChildren {
  cartLayoutRoute: typeof cartLayoutRouteWithChildren
}

const cartRouteChildren: cartRouteChildren = {
  cartLayoutRoute: cartLayoutRouteWithChildren,
}

const cartRouteWithChildren = cartRoute._addFileChildren(cartRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof appLayoutIndexRoute
  '': typeof appLayoutNotauthenticatedRouteWithChildren
  '/about': typeof appLayoutAboutRoute
  '/cart': typeof cartLayoutCartRoute
  '/sign-in': typeof appLayoutNotauthenticatedSignInRoute
  '/sign-up': typeof appLayoutNotauthenticatedSignUpRoute
  '/profile': typeof appLayoutAuthenticatedProfileLayoutRouteWithChildren
  '/shop/item/$handle': typeof appLayoutShopItemHandleRoute
  '/profile/change-password': typeof appLayoutAuthenticatedProfileLayoutChangePasswordRoute
  '/profile/edit': typeof appLayoutAuthenticatedProfileLayoutEditRoute
  '/profile/': typeof appLayoutAuthenticatedProfileLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appLayoutIndexRoute
  '': typeof appLayoutNotauthenticatedRouteWithChildren
  '/about': typeof appLayoutAboutRoute
  '/cart': typeof cartLayoutCartRoute
  '/sign-in': typeof appLayoutNotauthenticatedSignInRoute
  '/sign-up': typeof appLayoutNotauthenticatedSignUpRoute
  '/profile': typeof appLayoutAuthenticatedProfileLayoutIndexRoute
  '/shop/item/$handle': typeof appLayoutShopItemHandleRoute
  '/profile/change-password': typeof appLayoutAuthenticatedProfileLayoutChangePasswordRoute
  '/profile/edit': typeof appLayoutAuthenticatedProfileLayoutEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(cart)': typeof cartRouteWithChildren
  '/(cart)/_layout': typeof cartLayoutRouteWithChildren
  '/(app)/_layout/_authenticated': typeof appLayoutAuthenticatedRouteWithChildren
  '/(app)/_layout/_not_authenticated': typeof appLayoutNotauthenticatedRouteWithChildren
  '/(app)/_layout/about': typeof appLayoutAboutRoute
  '/(cart)/_layout/cart': typeof cartLayoutCartRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(app)/_layout/_not_authenticated/sign-in': typeof appLayoutNotauthenticatedSignInRoute
  '/(app)/_layout/_not_authenticated/sign-up': typeof appLayoutNotauthenticatedSignUpRoute
  '/(app)/_layout/_authenticated/profile': typeof appLayoutAuthenticatedProfileRouteWithChildren
  '/(app)/_layout/_authenticated/profile/_layout': typeof appLayoutAuthenticatedProfileLayoutRouteWithChildren
  '/(app)/_layout/shop/item/$handle': typeof appLayoutShopItemHandleRoute
  '/(app)/_layout/_authenticated/profile/_layout/change-password': typeof appLayoutAuthenticatedProfileLayoutChangePasswordRoute
  '/(app)/_layout/_authenticated/profile/_layout/edit': typeof appLayoutAuthenticatedProfileLayoutEditRoute
  '/(app)/_layout/_authenticated/profile/_layout/': typeof appLayoutAuthenticatedProfileLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/cart'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/shop/item/$handle'
    | '/profile/change-password'
    | '/profile/edit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/cart'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/shop/item/$handle'
    | '/profile/change-password'
    | '/profile/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_layout'
    | '/(cart)'
    | '/(cart)/_layout'
    | '/(app)/_layout/_authenticated'
    | '/(app)/_layout/_not_authenticated'
    | '/(app)/_layout/about'
    | '/(cart)/_layout/cart'
    | '/(app)/_layout/'
    | '/(app)/_layout/_not_authenticated/sign-in'
    | '/(app)/_layout/_not_authenticated/sign-up'
    | '/(app)/_layout/_authenticated/profile'
    | '/(app)/_layout/_authenticated/profile/_layout'
    | '/(app)/_layout/shop/item/$handle'
    | '/(app)/_layout/_authenticated/profile/_layout/change-password'
    | '/(app)/_layout/_authenticated/profile/_layout/edit'
    | '/(app)/_layout/_authenticated/profile/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  cartRoute: typeof cartRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  cartRoute: cartRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(cart)"
      ]
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_layout"
      ]
    },
    "/(app)/_layout": {
      "filePath": "(app)/_layout.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_layout/_authenticated",
        "/(app)/_layout/_not_authenticated",
        "/(app)/_layout/about",
        "/(app)/_layout/",
        "/(app)/_layout/shop/item/$handle"
      ]
    },
    "/(cart)": {
      "filePath": "(cart)",
      "children": [
        "/(cart)/_layout"
      ]
    },
    "/(cart)/_layout": {
      "filePath": "(cart)/_layout.tsx",
      "parent": "/(cart)",
      "children": [
        "/(cart)/_layout/cart"
      ]
    },
    "/(app)/_layout/_authenticated": {
      "filePath": "(app)/_layout/_authenticated.tsx",
      "parent": "/(app)/_layout",
      "children": [
        "/(app)/_layout/_authenticated/profile"
      ]
    },
    "/(app)/_layout/_not_authenticated": {
      "filePath": "(app)/_layout/_not_authenticated.tsx",
      "parent": "/(app)/_layout",
      "children": [
        "/(app)/_layout/_not_authenticated/sign-in",
        "/(app)/_layout/_not_authenticated/sign-up"
      ]
    },
    "/(app)/_layout/about": {
      "filePath": "(app)/_layout/about.tsx",
      "parent": "/(app)/_layout"
    },
    "/(cart)/_layout/cart": {
      "filePath": "(cart)/_layout/cart.tsx",
      "parent": "/(cart)/_layout"
    },
    "/(app)/_layout/": {
      "filePath": "(app)/_layout/index.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/_not_authenticated/sign-in": {
      "filePath": "(app)/_layout/_not_authenticated/sign-in.tsx",
      "parent": "/(app)/_layout/_not_authenticated"
    },
    "/(app)/_layout/_not_authenticated/sign-up": {
      "filePath": "(app)/_layout/_not_authenticated/sign-up.tsx",
      "parent": "/(app)/_layout/_not_authenticated"
    },
    "/(app)/_layout/_authenticated/profile": {
      "filePath": "(app)/_layout/_authenticated/profile",
      "parent": "/(app)/_layout/_authenticated",
      "children": [
        "/(app)/_layout/_authenticated/profile/_layout"
      ]
    },
    "/(app)/_layout/_authenticated/profile/_layout": {
      "filePath": "(app)/_layout/_authenticated/profile/_layout.tsx",
      "parent": "/(app)/_layout/_authenticated/profile",
      "children": [
        "/(app)/_layout/_authenticated/profile/_layout/change-password",
        "/(app)/_layout/_authenticated/profile/_layout/edit",
        "/(app)/_layout/_authenticated/profile/_layout/"
      ]
    },
    "/(app)/_layout/shop/item/$handle": {
      "filePath": "(app)/_layout/shop/item/$handle.tsx",
      "parent": "/(app)/_layout"
    },
    "/(app)/_layout/_authenticated/profile/_layout/change-password": {
      "filePath": "(app)/_layout/_authenticated/profile/_layout/change-password.tsx",
      "parent": "/(app)/_layout/_authenticated/profile/_layout"
    },
    "/(app)/_layout/_authenticated/profile/_layout/edit": {
      "filePath": "(app)/_layout/_authenticated/profile/_layout/edit.tsx",
      "parent": "/(app)/_layout/_authenticated/profile/_layout"
    },
    "/(app)/_layout/_authenticated/profile/_layout/": {
      "filePath": "(app)/_layout/_authenticated/profile/_layout/index.tsx",
      "parent": "/(app)/_layout/_authenticated/profile/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
